apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
type: Opaque
stringData:
  ssh_host_ed25519_key: {{ .Values.ssh.sshHostEd25519Key }}
  ssh_host_ed25519_key.pub: {{ .Values.ssh.sshHostEd25519KeyPub }}
  ssh_host_rsa_key: {{ .Values.ssh.sshHostRsaKey }}
  ssh_host_rsa_key.pub: {{ .Values.ssh.sshHostRsaKeyPub }}
