apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
type: Opaque
stringData:
  ssh_host_ed25519_key: {{Values.ssh.ssh-host-ed25519-key}}
  ssh_host_ed25519_key.pub: {{Values.ssh.ssh-host-ed25519-key-pub}}
  ssh_host_rsa_key: {{Values.ssh.ssh-host-rsa-key}}
  ssh_host_rsa_key.pub: {{Values.ssh.ssh-host-rsa-key-pub}}
